### ISSUE TITLE
make.coffee --> make.js

### ISSUE THREAD

**Issue by sailxjx** [mvc-works/mission#1]
通用性更强，而且还要发布到npm，还是把make.coffee改成make.js吧？

**Comment by tiye** [comment]
`make.coffee` 是写进 `.npmignore` 里的, 用到的人只有是协助我开发项目的人.
考虑到目前代码太个性化, 即便公司要用, 估计也还要进行拆分.
考虑到目前只有我一个人做, 而且 `.js` 文件我绝对不会去维护, 这个仓库里不计划改.
